In [2]:
import numpy as np

code_space = []

class Error:
    def __init__(self, probability, type):
        self.probability = probability
        self.type = type

In [ ]:
class Circuit:
    def __init__(self, qubits):
        pass

In [ ]:
class RepititionCode:
    def __init__(self, distance):
        self.distance = distance

        self.qubits = np.zeros(distance)

    def x_error(self, component):
        if component > self.distance:
            raise IndexError

        self.qubits[component] = int(not self.qubits[component])


    def z_error(self, component):
        if component > self.distance:
            raise IndexError

In [ ]:
dim = 5
R2 = 1 / np.sqrt(2)

def H(bit):

    had = np.array([
        [1*R2, 1*R2],
        [1*R2, -1*R2]])

    id = np.array([
        [1, 0],
        [0, 1]
    ])

    if dim == 1:
        return had

    chain = np.zeros(dim)
    chain[bit] = 1

    m0 = had if chain[0] == 1 else id
    m1 = had if chain[1] == 1 else id
    prod = np.kron(m0, m1)

    if dim == 2:
        return prod
    
    for i in chain[2:]:
        m = had if i == 1 else id
        prod = np.kron(prod, m)

    return prod


[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [70]:
def Z(bit):

    z = np.diag([1, -1])
    id = np.diag([1, 1])

    if dim == 1:
        return z

    chain = np.zeros(dim)
    chain[bit] = 1

    m0 = z if chain[0] == 1 else id
    m1 = z if chain[1] == 1 else id
    prod = np.kron(m0, m1)

    if dim == 2:
        return prod
    
    for i in chain[2:]:
        m = z if i == 1 else id
        prod = np.kron(prod, m)

    return prod

def X(bit):

    x = np.array(
        [0, 1],
        [1, 0]
    )
    id = np.diag([1, 1])

    if dim == 1:
        return x

    chain = np.zeros(dim)
    chain[bit] = 1

    m0 = x if chain[0] == 1 else id
    m1 = x if chain[1] == 1 else id
    prod = np.kron(m0, m1)

    if dim == 2:
        return prod
    
    for i in chain[2:]:
        m = x if i == 1 else id
        prod = np.kron(prod, m)

    return prod

In [74]:
dim = 5

def CNOT(control, target):
    x = np.array(
            [[0, 1],
            [1, 0]]
        )
    id = np.diag([1, 1])

    m = np.zeros([2**dim, 2**dim])

    for state in range(2**dim):
        binary = np.zeros(dim)
        for i, digit in enumerate(reversed(bin(state)[2:])):
            binary[-(i + 1)] = digit

        binary[target] = (binary[control] + binary[target]) % 2

        num = 0
        for i, comp in enumerate(reversed(binary)):
            num += (comp * (2**i))
            # print(comp, i, num)

        m[state, int(num)] = 1

    return m

In [79]:
dim = 3

ZERO = np.array([[1]] + [[0]] * (2**dim - 1))
print(ZERO)

I = np.diag(np.ones(2**dim))

I_1 = np.array([
    [1, 0],
    [0, 1]
])

CX = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

CXI = np.kron(CX, I_1)
ICX = np.kron(I_1, CX)

stab = CNOT(0, 2) @ CNOT(0, 1) @ H(0) @ ZERO
stab

[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678]])