In [2]:
import numpy as np

code_space = []

class Error:
    def __init__(self, probability, type):
        self.probability = probability
        self.type = type

In [ ]:
class Circuit:
    def __init__(self, qubits):
        pass

In [ ]:
class RepititionCode:
    def __init__(self, distance):
        self.distance = distance

        self.qubits = np.zeros(distance)

    def x_error(self, component):
        if component > self.distance:
            raise IndexError

        self.qubits[component] = int(not self.qubits[component])


    def z_error(self, component):
        if component > self.distance:
            raise IndexError

        

        


In [ ]:
qubit = [1, 0]

input = [qubit, qubit, qubit]
H = np.array([[1, 1], [1, -1]])
I = np.array([[1, 0], [0, 1]])

input[0] = H @ input[0]
input

[array([1, 1]), [1, 0], [1, 0]]

In [ ]:
dim = 3
R2 = 1 / np.sqrt(2)

def H(bit):

    had = np.array([
        [1*R2, 1*R2],
        [1*R2, -1*R2]])

    id = np.array([
        [1, 0],
        [0, 1]
    ])

    if dim == 1:
        return had

    chain = np.zeros(dim)
    chain[bit] = 1

    m0 = had if chain[0] == 1 else id
    m1 = had if chain[1] == 1 else id
    prod = np.kron(m0, m1)

    if dim == 2:
        return prod
    
    for i in chain[2:]:
        m = had if i == 1 else id
        prod = np.kron(prod, m)

    return prod

ZERO = np.array([[1]] + [[0]] * (2**dim - 1))
print(ZERO)

I = np.diag(np.ones(2**dim))
print(I)

I = np.array([
    [1, 0],
    [0, 1]
])

CX = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

CXI = np.kron(CX, I)
ICX = np.kron(I, CX)

stab = ICX @ CXI @ H(0) @ ZERO
stab

[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678]])